spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Library-Software
    username: postgres
    password: Suryansh@1904
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #          hibernate:
  #            dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

per-day-amount: 15
fine-pdf-folder: "/home/suryansh/Desktop/Library-Software/Fine Pdf/"
base-url: "http://localhost:8080/"
jwt-exp-time-min: 60